name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Collect test reports
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: 'reports/*.xml'
